// Manifest read/write + runtime artifact emission.
// images.manifest.json — full record (review page + incremental builds).
// images.js            — lean window.BR_IMAGES with ONLY shippable entries
//                        (confidence auto/approved); review/rejected items
//                        fall back to text in the app.
import fs from 'node:fs';

export const SHIPPABLE = new Set(['auto', 'approved']);

export function loadJson(file, fallback) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; }
}

function sortedByKey(obj) {
  return Object.fromEntries(Object.entries(obj).sort(([a], [b]) => a.localeCompare(b)));
}

export function writeManifest(file, items, version = 1) {
  // No timestamp at the top level: repeat runs with identical content must
  // produce a zero git diff.
  const doc = { version, items: sortedByKey(items) };
  fs.writeFileSync(file, JSON.stringify(doc, null, 2) + '\n');
}

export function writeImagesJs(file, items) {
  const out = {};
  for (const [key, e] of Object.entries(sortedByKey(items))) {
    if (!SHIPPABLE.has(e.confidence) || !e.url) continue;
    const entry = { u: e.url, f: e.fit || 'contain', x: e.focusX ?? 50, y: e.focusY ?? 50 };
    if (e.pad) entry.p = 1;
    out[key] = entry;
  }
  const body = Object.entries(out)
    .map(([k, v]) => `${JSON.stringify(k)}:${JSON.stringify(v)}`)
    .join(',\n');
  fs.writeFileSync(file,
    '// Generated by tools/build-images — do not edit by hand.\n' +
    '// Maps item keys to pre-vetted image URLs + crop focal points.\n' +
    'window.BR_IMAGES = {\n' + body + '\n};\n');
  return Object.keys(out).length;
}

export function summarize(items) {
  const byStatus = {};
  const reviewByReason = {};
  const byCategory = {};
  for (const e of Object.values(items)) {
    byStatus[e.confidence] = (byStatus[e.confidence] || 0) + 1;
    byCategory[e.category] = byCategory[e.category] || { total: 0, shipped: 0 };
    byCategory[e.category].total++;
    if (SHIPPABLE.has(e.confidence)) byCategory[e.category].shipped++;
    if (e.confidence === 'review') {
      const r = (e.reviewReason || 'unknown').split(':')[0];
      reviewByReason[r] = (reviewByReason[r] || 0) + 1;
    }
  }
  return { byStatus, reviewByReason, byCategory };
}
